### ISSUE TITLE
how to build on linux

### ISSUE THREAD

**Issue by sxyizhiren** [Paracel/QSanguosha-Para#14]
does it possible to build a server on linux like UBUNTU?

**Comment by BeginnerSlob** [comment]
maybe u can use Qt Creator to build this without breakpad

**Comment by Fsu0413** [comment]
@BeginnerSlob nope...It can only be built using Visual Studio, some codes here is not supported by GNU GCC.

**Comment by BeginnerSlob** [comment]
@Fsu0413 I dont care=.=

**Comment by sxyizhiren** [comment]
@Fsu0413 it's a bad news, =-=

**Comment by Paracel** [comment]
No
