### ISSUE TITLE
报告几个bug

### ISSUE THREAD

**Issue by huoshan12345** [Paracel/QSanguosha-Para#2]
1.貌似潜袭的发动时机写错了，event里面是 EventPhaseStart但是时机判断里就成EventPhaseChanging，所以潜袭无法发动

2.有时候手牌会变成负数（这个出现时间不确定）

3.火攻有时候无法弃置（能弃置的牌会变亮，但是无法点确定，无鸡肋）

**Comment by Paracel** [comment]
1.马上改= =
2.除了孙权和孙尚香还有谁出现过这个问题？
3.这个应该已经修了

**Comment by huoshan12345** [comment]
1.没事了
2.是谁没注意唉，但是肯定见过孙权的
3.我下新码再试试

para君辛苦了啊
